### ISSUE TITLE
React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead.

### ISSUE THREAD

**Issue by adamtal3** [gaearon/react-document-title#39]

**Comment by MichaelDeBoey** [comment]
`React.createClass` has been deprecated to since [React v15.5.0](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#new-deprecation-warnings).

The following warning is displayed if that version of React is used:
`Warning: DocumentTitle: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

CC: @gaearon

**Comment by MichaelDeBoey** [comment]
@adamtal3: Just saw this will be closed in #38 :-)

**Comment by gaearon** [comment]
Fixed in 2.0.3, please verify.

**Comment by MichaelDeBoey** [comment]
@gaearon This is fixed :-)
